#Standard boilerplate makefile stuff. Ensure bmake compatibility (model waymake to imitate bmake)

CC = clang
LD = ld.lld
ASM = nasm

MAKE = bmake	##Absolutely force us to use bmake!!!

all:
	echo $(ASM)
	echo $(CC)
	echo $(LD)
##Stub for now.

