all:
	##TODO

pull:
	git clone https://github.com/bSchnepp/FreedomCore.git	##Fix so the 'src' tree is what's pulled in.
	mkdir Waymake && cd Waymake && git clone https://github.com/bSchnepp/Waymake.git
